name: common_widgets
description: "Shared reusable widgets for Chirag Associates apps"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  fl_chart: ^0.70.2
  go_router: ^14.8.1
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  http: ^1.2.2
  cupertino_icons: ^1.0.8
