name: ecommerce_app
description: "Chirag Associates - Dynamic B2B E-Commerce Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  common_widgets:
    path: ../common_widgets
  go_router: ^14.8.1
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  no_screenshot: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/demo_jewellery/bridal_necklace.jpg
    - assets/demo_jewellery/bridal_necklace_detail_motif.jpg
    - assets/demo_jewellery/bridal_necklace_detail_pendant.jpg
    - assets/demo_jewellery/bridal_set.jpg
    - assets/demo_jewellery/bridal_set_detail_earrings.jpg
    - assets/demo_jewellery/bridal_set_detail_necklace.jpg
    - assets/demo_jewellery/gold_bangles.jpg
    - assets/demo_jewellery/gold_bangles_detail_left.jpg
    - assets/demo_jewellery/gold_bangles_detail_right.jpg
    - assets/demo_jewellery/gold_earrings.jpg
    - assets/demo_jewellery/gold_earrings_detail_left.jpg
    - assets/demo_jewellery/gold_earrings_detail_right.jpg
    - assets/demo_jewellery/gold_pendant.jpg
    - assets/demo_jewellery/gold_pendant_chain_detail.jpg
    - assets/demo_jewellery/gold_pendant_detail.jpg
    - assets/demo_jewellery/gold_ring.jpg
    - assets/demo_jewellery/gold_ring_detail_band.jpg
    - assets/demo_jewellery/gold_ring_detail_stone.jpg
